apiVersion: v1
kind: ConfigMap
metadata:
  name: springk8s
data:
  mongo_port: "27017"
  mongo_host: {{ .Release.Name }}-mongodb
  mongo_db: springk8s
  mongo_username: springk8s
  mongo_root-username: root
